### ISSUE TITLE
Birst list spaces failing due to envcrypt

### ISSUE THREAD

**Issue by marutinandanpandya** [gnilrets/Birst_Command#5]
```$ birstcl -c list_spaces
/Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/envcrypt-0.1.2/lib/envcrypt/envcrypt.rb:54:in `update': can't convert Configatron::Store to String (Configatron::Store#to_str gives Configatron::Store) (TypeError)
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/envcrypt-0.1.2/lib/envcrypt/envcrypt.rb:54:in `decrypt'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/Birst_Command-0.6.1/lib/birst_command/session.rb:133:in `decrypt'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/Birst_Command-0.6.1/lib/birst_command/session.rb:42:in `login'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/Birst_Command-0.6.1/lib/birst_command/session.rb:120:in `login_and_run'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/Birst_Command-0.6.1/lib/birst_command/session.rb:24:in `initialize'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/Birst_Command-0.6.1/bin/birstcl:92:in `new'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/Birst_Command-0.6.1/bin/birstcl:92:in `execute_command'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/Birst_Command-0.6.1/bin/birstcl:19:in `run'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/gems/Birst_Command-0.6.1/bin/birstcl:103:in `<top (required)>'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/bin/birstcl:23:in `load'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/bin/birstcl:23:in `<main>'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/marutinandan_pandya/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

Steps done:
1. gem install Birst_Command
2. touch ~/.birstcl
3. Fill in required entries in .birstcl
4. encrypt password
5. run "birstcl -c list_spaces"

**Comment by gnilrets** [comment]
Haha, that envcrypt thing was a bit half-baked.  Sorry about that.  I don't have access to a Birst resource anymore to troubleshoot this at all.  Your best bet might be to fork this repo and strip out the envcrypt stuff.
